[package]
name = "rust_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.6"
tokio = { version = "1", features = ["full"] }
prost = "0.9"  # 用于编译 .proto 文件
tonic-build = "0.6"  # 用于生成 Rust 代码

